package com.example.app.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF4E7743) // màu của nút chính, thanh toolbars
    // primaryLight: nền của các thành phần chính.
val onPrimaryLight = Color(0xFF000000)
// onPrimaryLight: màu chữ/icon hiển thị trên nền primaryLight.
val primaryContainerLight = Color(0xFF295020) // Phiên bản nhạt hơn của primary, thường dùng cho container (ví dụ Card, Chip).
val onPrimaryContainerLight = Color(0xFFC1EFAF) // onPrimaryContainerLight: màu chữ trên container.
val secondaryLight = Color(0xFF406835)
// Các màu phụ để phối với primary, giúp tạo chiều sâu giao diện.
//
//Ví dụ secondary có thể dùng cho nút phụ, tertiary cho highlights.
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC1EFAF)
val onSecondaryContainerLight = Color(0xFF295020)
val tertiaryLight = Color(0xFF3A693B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBBF0B5)
val onTertiaryContainerLight = Color(0xFF225025)
val errorLight = Color(0xFF416835)
// 👉 Màu cảnh báo lỗi (vd: nút xoá, cảnh báo form sai).
//
//onErrorLight: chữ trắng trên nền đỏ.
//
//errorContainerLight: màu nền nhạt cảnh báo.
//
//onErrorContainerLight: chữ trên nền nhạt.
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFC2EFAE)
val onErrorContainerLight = Color(0xFF2A4F1F)
// Màu nền & bề mặt
val backgroundLight = Color(0xFFF8FBF1) // Màu nền toàn app & màu chữ trên nền.
val onBackgroundLight = Color(0xFF191D17)
val surfaceLight = Color(0xFFF8FBF1)
val onSurfaceLight = Color(0xFF191D17)
val surfaceVariantLight = Color(0xFFDFE4D7)
val onSurfaceVariantLight = Color(0xFF43483F)
val outlineLight = Color(0xFF73796E) // Màu đường viền (border, divider).
val outlineVariantLight = Color(0xFFC3C8BC)
val scrimLight = Color(0xFF000000) //Màu mờ overlay (vd: khi mở dialog, scrim che phía sau).
val inverseSurfaceLight = Color(0xFF2E322B) // 👉 Màu primary đảo, thường dùng cho dark/light blending.
val inverseOnSurfaceLight = Color(0xFFEFF2E8)
val inversePrimaryLight = Color(0xFFA5D395)
val surfaceDimLight = Color(0xFFD8DBD2)
val surfaceBrightLight = Color(0xFFF8FBF1)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F5EB)
val surfaceContainerLight = Color(0xFFECEFE5)
val surfaceContainerHighLight = Color(0xFFE6E9E0)
val surfaceContainerHighestLight = Color(0xFFE1E4DA)

val primaryLightMediumContrast = Color(0xFF183E11)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF4E7743)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF183E11)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF4E7743)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF0F3F16)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF487848)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF193E10)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFF4F7742)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF8FBF1)
val onBackgroundLightMediumContrast = Color(0xFF191D17)
val surfaceLightMediumContrast = Color(0xFFF8FBF1)
val onSurfaceLightMediumContrast = Color(0xFF0E120D)
val surfaceVariantLightMediumContrast = Color(0xFFDFE4D7)
val onSurfaceVariantLightMediumContrast = Color(0xFF32382F)
val outlineLightMediumContrast = Color(0xFF4E544A)
val outlineVariantLightMediumContrast = Color(0xFF696F64)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2E322B)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEFF2E8)
val inversePrimaryLightMediumContrast = Color(0xFFA5D395)
val surfaceDimLightMediumContrast = Color(0xFFC4C8BE)
val surfaceBrightLightMediumContrast = Color(0xFFF8FBF1)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF2F5EB)
val surfaceContainerLightMediumContrast = Color(0xFFE6E9E0)
val surfaceContainerHighLightMediumContrast = Color(0xFFDBDED5)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD0D3C9)

val primaryLightHighContrast = Color(0xFF0D3407)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF2B5222)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF0D3407)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF2B5222)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF02340C)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF245327)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF0E3406)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF2C5221)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF8FBF1)
val onBackgroundLightHighContrast = Color(0xFF191D17)
val surfaceLightHighContrast = Color(0xFFF8FBF1)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDFE4D7)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF282E25)
val outlineVariantLightHighContrast = Color(0xFF454B41)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2E322B)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFA5D395)
val surfaceDimLightHighContrast = Color(0xFFB7BAB1)
val surfaceBrightLightHighContrast = Color(0xFFF8FBF1)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEFF2E8)
val surfaceContainerLightHighContrast = Color(0xFFE1E4DA)
val surfaceContainerHighLightHighContrast = Color(0xFFD2D6CC)
val surfaceContainerHighestLightHighContrast = Color(0xFFC4C8BE)

val primaryDark = Color(0xFF9B4DE0)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF4C1E6C)
val onPrimaryContainerDark = Color(0xFF4A1C69)
val secondaryDark = Color(0xFFA5D395)
val onSecondaryDark = Color(0xFF11380B)
val secondaryContainerDark = Color(0xFF295020)
val onSecondaryContainerDark = Color(0xFFC1EFAF)
val tertiaryDark = Color(0xFFA0D49B)
val onTertiaryDark = Color(0xFF073910)
val tertiaryContainerDark = Color(0xFF225025)
val onTertiaryContainerDark = Color(0xFFBBF0B5)
val errorDark = Color(0xFFA6D394)
val onErrorDark = Color(0xFF13380A)
val errorContainerDark = Color(0xFF2A4F1F)
val onErrorContainerDark = Color(0xFFC2EFAE)
val backgroundDark = Color(0xFF170F23)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF11140F)
val onSurfaceDark = Color(0xFFE1E4DA)
val surfaceVariantDark = Color(0xFF43483F)
val onSurfaceVariantDark = Color(0xFFC3C8BC)
val outlineDark = Color(0xFF8D9387)
val outlineVariantDark = Color(0xFF43483F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E4DA)
val inverseOnSurfaceDark = Color(0xFF2E322B)
val inversePrimaryDark = Color(0xFF406836)
val surfaceDimDark = Color(0xFF11140F)
val surfaceBrightDark = Color(0xFF363A34)
val surfaceContainerLowestDark = Color(0xFF0B0F0A)
val surfaceContainerLowDark = Color(0xFF191D17)
val surfaceContainerDark = Color(0xFF1D211B)
val surfaceContainerHighDark = Color(0xFF272B25)
val surfaceContainerHighestDark = Color(0xFF32362F)

val primaryDarkMediumContrast = Color(0xFFBAE9AA)
val onPrimaryDarkMediumContrast = Color(0xFF052D02)
val primaryContainerDarkMediumContrast = Color(0xFF719C64)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFBBE9AA)
val onSecondaryDarkMediumContrast = Color(0xFF052D02)
val secondaryContainerDarkMediumContrast = Color(0xFF719C63)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFB5EAB0)
val onTertiaryDarkMediumContrast = Color(0xFF002D08)
val tertiaryContainerDarkMediumContrast = Color(0xFF6B9D69)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFBCE9A8)
val onErrorDarkMediumContrast = Color(0xFF072D02)
val errorContainerDarkMediumContrast = Color(0xFF729C62)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF11140F)
val onBackgroundDarkMediumContrast = Color(0xFFE1E4DA)
val surfaceDarkMediumContrast = Color(0xFF11140F)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF43483F)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD9DED1)
val outlineDarkMediumContrast = Color(0xFFAEB4A7)
val outlineVariantDarkMediumContrast = Color(0xFF8C9287)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE1E4DA)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF272B25)
val inversePrimaryDarkMediumContrast = Color(0xFF2A5121)
val surfaceDimDarkMediumContrast = Color(0xFF11140F)
val surfaceBrightDarkMediumContrast = Color(0xFF42463F)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF050804)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1F19)
val surfaceContainerDarkMediumContrast = Color(0xFF252923)
val surfaceContainerHighDarkMediumContrast = Color(0xFF30342D)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3B3F38)

val primaryDarkHighContrast = Color(0xFFCEFDBC)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFA1CF92)
val onPrimaryContainerDarkHighContrast = Color(0xFF000F00)
val secondaryDarkHighContrast = Color(0xFFCEFDBC)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA1CF92)
val onSecondaryContainerDarkHighContrast = Color(0xFF000F00)
val tertiaryDarkHighContrast = Color(0xFFC8FEC2)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF9CD098)
val onTertiaryContainerDarkHighContrast = Color(0xFF000F02)
val errorDarkHighContrast = Color(0xFFCFFDBB)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFA3CF91)
val onErrorContainerDarkHighContrast = Color(0xFF010F00)
val backgroundDarkHighContrast = Color(0xFF11140F)
val onBackgroundDarkHighContrast = Color(0xFFE1E4DA)
val surfaceDarkHighContrast = Color(0xFF11140F)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF43483F)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEDF2E4)
val outlineVariantDarkHighContrast = Color(0xFFBFC4B8)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE1E4DA)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF2A5121)
val surfaceDimDarkHighContrast = Color(0xFF11140F)
val surfaceBrightDarkHighContrast = Color(0xFF4D514A)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1D211B)
val surfaceContainerDarkHighContrast = Color(0xFF2E322B)
val surfaceContainerHighDarkHighContrast = Color(0xFF393D36)
val surfaceContainerHighestDarkHighContrast = Color(0xFF444841)







